packages:
  - global-ui
  - mobile-ui
catalog:
  "@changesets/changelog-github": ^0.5.0
  "@changesets/cli": ^2.27.7
  "@ember/jquery": ^2.0.0
  "@ember/string": ^3.1.1
  "@ember/test-waiters": ^3.1.0
  "@embroider/addon-dev": ^7.1.1
  "@embroider/addon-shim": ^1.9.0
  "@embroider/macros": ^1.16.5
  "@embroider/test-setup": ^4.0.0
  "@fortawesome/ember-fontawesome": ^1.0.0
  "@fortawesome/fontawesome-svg-core": ^6.7.2
  "@fortawesome/free-brands-svg-icons": ^6.7.2
  "@fortawesome/pro-light-svg-icons": ^6.7.2
  "@fortawesome/pro-solid-svg-icons": ^6.7.2
  "@glimmer/component": ^1.1.2
  "@glimmer/tracking": ^1.1.2
  "@glint/core": ^1.5.0
  "@glint/environment-ember-loose": ^1.5.0
  "@glint/environment-ember-template-imports": ^1.5.0
  "@glint/template": ^1.5.0
  "@nx/devkit": 21.2.0
  "@nx/eslint": 21.2.0
  "@nx/eslint-plugin": 21.2.0
  "@nx/jest": 21.2.0
  "@nx/js": 21.2.0
  "@nx/plugin": 21.2.0
  "@nx/rollup": 21.2.0
  "@rollup/plugin-babel": ^6.0.4
  "@swc-node/register": ~1.9.1
  "@swc/cli": ~0.7.7
  "@swc/core": ~1.12.1
  "@swc/helpers": ~0.5.17
  "@types/chai": ^5.0.1
  "@types/ember__modifier": ^4.0.9
  "@types/ember__string": ^3.16.3
  "@types/ember-data": 4.4.16
  "@types/ember-data__model": 4.0.5
  "@types/ember-data__store": 4.0.7
  "@types/ember-resolver": ^5.0.13
  "@types/jquery": ^3.5.30
  "@types/mocha": ^10.0.10
  "@types/rsvp": ^4.0.9
  "@types/sinon": 17.0.4
  "@types/vimeo__player": ^2.18.3
  "@vimeo/player": ^2.24.0
  active-model-adapter: ^4.0.1
  babel-eslint: ^10.1.0
  broccoli-asset-rev: ^3.0.0
  broccoli-string-replace: 0.1.2
  chai: ^4.3.10
  classnames: ^2.3.2
  cross-env: ^7.0.3
  decorator-transforms: ^2.3.0
  ember-ajax: ^5.1.2
  ember-animated: ^1.1.3
  ember-cli: ~3.28.6
  ember-cli-app-version: ^6.0.1
  ember-cli-babel: ^8.2.0
  ember-cli-clean-css: ^3.0.0
  ember-cli-dependency-checker: ^3.3.2
  ember-cli-dependency-lint: ^2.0.0
  ember-cli-htmlbars: ^6.3.0
  ember-cli-inject-live-reload: ^2.1.0
  ember-cli-moment-shim: ^3.8.0
  ember-cli-sass: ^11.0.1
  ember-cli-sri: ^2.1.1
  ember-cli-terser: ^4.0.2
  ember-concurrency: ^3.1.1
  ember-css-transitions: ^4.4.1
  ember-data: ~4.4.0
  ember-disable-prototype-extensions: ^1.1.3
  ember-export-application-global: ^2.0.1
  ember-file-upload: ^8.4.1
  ember-freestyle: ^0.21.0
  ember-in-viewport: ^4.1.0
  ember-inflector: ^5.0.2
  ember-keyboard: ^8.2.1
  ember-load-initializers: ^2.1.2
  ember-modifier: ^4.2.0
  ember-page-title: ^8.2.3
  ember-power-select: ~7.2.0
  ember-simulant-test-helpers: ^0.3.2
  ember-source: ~4.4.0
  ember-source-channel-url: ^3.0.0
  ember-template-imports: ^4.1.1
  ember-truth-helpers: ^4.0.3
  ember-wormhole: ^0.6.0
  eslint-plugin-import: ^2.29.1
  eslint-plugin-node: ^11.1.0
  eslint-plugin-simple-import-sort: ^8.0.0
  focus-trap: ^7.6.2
  get-sass-vars: ^4.0.2
  loader.js: ^4.7.0
  macro-decorators: ^0.1.2
  mocha: ^11.1.0
  mocha-junit-reporter: ^2.2.1
  moment: 2.25.3
  normalize.css: ^8.0.1
  npm-run-all: ^4.1.5
  nx: 21.2.0
  prettier-plugin-ember-template-tag: ^1.1.0
  release-it: ^13.6.0
  release-it-lerna-changelog: ^2.3.0
  rollup-plugin-shell: ^1.0.9
  rollup-plugin-styles: ^4.0.0
  sinon: 20.0.0
  stylelint: ^16.7.0
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-sass-guidelines: ^12.0.0
  stylelint-scss: ^6.4.1
  tracked-built-ins: ^3.3.0
  ts-node: ^10.9.2
  tslib: ^2.3.0
  yaml: ^2.7.0
  zapier-platform-cli: 16.3.1
  zapier-platform-core: 16.3.1
